[package]
name = "nast-storage"
version.workspace = true
edition.workspace = true

[dependencies]
nast-model = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
nast-cards.workspace = true

[dev-dependencies]
tempfile.workspace = true
